[package]
name = "linux"
version = "0.1.0"
authors = ["Lance Hart <me@lancehart.ca>"]
edition = "2021"
description = "Linux raw bindings"
repository = "https://github.com/shipsimfan/lib-linux"
license = "GPL-3.0-or-later"
publish = false
